title: NoWisdomS
author:
    name: NoVarYe
    email: jidijam.olk@outlook.com

lang: en
# Change to your timezone › https://kevinnovak.github.io/Time-Zone-Picker
timezone: Asia/Shanghai

# "欢迎漫步于我的博客天地，这里融合了科技的前沿、生活的智慧与旅行的奇遇。
# 探索每一篇文章，品味独特见解，从中汲取灵感与智慧，为你的生活增添色彩。"
description: >-
    "Welcome to the world of my blog, where the cutting edge of technology, 
    the wisdom of daily life, and the wonders of travel come together. 
    Explore each article, savor unique insights, 
    and draw inspiration and wisdom to add color to your life."

# the avatar on sidebar, support local or CORS resources
avatar: /assets/avatars/avatar.jpg

# Site settings
# domain: No4Var2Ye.github.io
url: https://No4Var2Ye.github.io
baseurl: ""
feed:
    path: "feed.xml"

plugins:
    - jekyll-feed
    - jekyll-remote-theme
    - jekyll-seo-tag
    - jekyll-paginate
    - jekyll-sitemap

# Build settings
# theme: VarAtoZ
# remote_theme: No4Var2Ye/VarAtoZ

# Web Analytics Settings
sass:
    style: compressed

analytics:
    google:
        id: G-MRH0X2Y200
    goatcounter:
        id: # fill in your GoatCounter ID
    umami:
        id: # fill in your Umami ID
        domain: # fill in your Umami domain
    matomo:
        id: # fill in your Matomo ID
        domain: # fill in your Matomo domain

google_analytics: G-MRH0X2Y200

disqus:
    shortname: novarye

comments:
    # Global switch for the post comment system. Keeping it empty means disabled.
    provider: giscus
    # The provider options are as follows:
    disqus:
        shortname: novarye
    # utterances settings › https://utteranc.es/
    utterances:
        repo: # <gh-username>/<repo>
        issue_term: # < url | pathname | title | ...>
    # Giscus options › https://giscus.app
    giscus:
        repo: winxuan/winxuan.github.io # <gh-username>/<repo>
        repo_id: R_kgDOK9xKpw
        category: Comments
        category_id: DIC_kwDOK9xKp84CcIV2
        mapping: pathname # optional, default to 'pathname'
        input_position: bottom # optional, default to 'bottom'
        lang: zh-CN # optional, default to the value of `site.lang`
        reactions_enabled: 1 # optional, default to the value of `1`

pagination:
    enabled: true
    per_page: 10
    title: "Page {{ page.number }}"
paginate:

# Collection settings
# TODO: Add your collections here.
collections:
    note:
        output: true
        permalink: /note/:path/
    design:
        output: true
        permalink: /design/:path/
    life:
        output: true
        permalink: /life/:path/
    code:
        output: true
        permalink: /code/:path/
    cg:
        output: true
        permalink: /cg/:path/
    ai:
        output: true
        permalink: /ai/:path/

# GitHub Pages settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
    # parse_block_html: true
    syntax_highlighter: rouge
    # parse_span_html: true
    syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
        css_class: highlight
        # default_lang: console
        span:
            line_numbers: false
        block:
            line_numbers: true
            start_line: 1

# Markdown settings
markdown: kramdown

# Post settings
excerpt_separator: "<!--more-->"

# Theme-specific settings

# If you want to link only specific pages in your header, use this and add the path to the pages
# in order as they should show up.
# TODO: Add the pages you want to show up in the header.
header_pages:
    # - blog.md
    # - contact.md
    - webgl-example.html
    - about.markdown

# TODO: Set to `true` to show excerpts on the homepage.
#show_excerpts: false

varatoz:
    # Available skins are:
    # classic	             Default, light color scheme.
    # dark	                 Dark variant of the classic skin.
    skin: classic

    # VarAtoZ date format.
    # The default value is "%b %d, %Y" (e.g. Nov 14, 2023)
    # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
    date_format: "%b %d, %Y"

    # Social media
    social_accounts:
        dribbble_username: NoVarYe
        # facebook_username: jekyll
        github_username: NoVarYe
        # gitlab_username: NoVarYe
        # google_scholar_username: qc6CJjYAAAAJ
        pinterest_username: Novarye G
        stackoverflow_user_id: 23326673
        twitter_username: _NoMem
        # youtube_username: jekyll

    # Generate social links in footer.
    social_links:
        #     - { platform: devto, user_url: "https://dev.to/jekyll" }
        - { platform: dribbble, user_url: "https://dribbble.com/NoVarYe" }
        # - { platform: facebook, user_url: "https://www.facebook.com/jekyll" }
        #     - { platform: flickr, user_url: "https://www.flickr.com/photos/jekyll" }
        - { platform: github, user_url: "https://github.com/No4Var2Ye" }
        # - { platform: gitlab, user_url: "https://gitlab.com/No4Var2Ye" }
        # - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
        #     - { platform: instagram, user_url: "https://www.instagram.com/jekyll" }
        #     - { platform: keybase, user_url: "https://keybase.io/jekyll" }
        #     - { platform: linkedin, user_url: "https://www.linkedin.com/in/jekyll" }
        #     - { platform: microdotblog, user_url: "https://micro.blog/jekyll" }
        - { platform: pinterest, user_url: "https://www.pinterest.com/novaryeg" }
        - { platform: stackoverflow, user_url: "https://stackoverflow.com/users/23326673/novarye" }
        #     - { platform: telegram, user_url: "https://t.me/jekyll" }
        - { platform: twitter, user_url: "https://twitter.com/NovaryeG" }
        # - { platform: x, user_url: "https://x.com/NovaryeG" }
        # - { platform: youtube, user_url: "https://www.youtube.com/jekyll" }

exclude:
    - "*.gem"
    - "*.gemspec"
    - README.md
    - LICENSE.md
    - CONTRIBUTING.md
    - SECURITY.md
    - rollup.config.js
    - package*.json
